In [28]:
import pandas as pd

amino_values = {
    'Ala': [8.47, 8.95],
    'Cys': [1.39, 0.47],
    'Asp': [5.97, 5.91],
    'Glu': [6.32, 4.78],
    'Thr': [5.79, 6.54],
    'Phe': [3.91, 3.68],
    'Gly': [7.82, 8.54],
    'His': [2.26, 1.25],
    'Ile': [5.71, 4.77],
    'Lys': [5.76, 4.93],
    'Leu': [8.48, 8.78],
    'Met': [2.21, 1.56],
    'Asn': [4.54, 5.74],
    'Trp': [1.44, 1.24],
    'Pro': [4.63, 3.74],
    'Gln': [3.82, 4.75],
    'Arg': [4.93, 5.24],
    'Ser': [5.94, 8.05],
    'Tyr': [3.58, 4.13],
    'Val': [7.02, 6.76]
}


amino_acids_dict = {
    'Ala': 'A',
    'Arg': 'R',
    'Asn': 'N',
    'Asp': 'D',
    'Cys': 'C',
    'Gln': 'Q',
    'Glu': 'E',
    'Gly': 'G',
    'His': 'H',
    'Ile': 'I',
    'Leu': 'L',
    'Lys': 'K',
    'Met': 'M',
    'Phe': 'F',
    'Pro': 'P',
    'Ser': 'S',
    'Thr': 'T',
    'Trp': 'W',
    'Tyr': 'Y',
    'Val': 'V'
}


input_sequences = [
    'RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA',
    'AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA',
    'AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI'
]

table = pd.DataFrame(columns=['A', 'B', 'Group'])
composition_table = pd.DataFrame(columns=amino_acids_dict.values())

for i in input_sequences:
    aas = list(i)
    composition_table = composition_table.append(pd.Series({aa: aas.count(aa)*100/len(aas) for aa in amino_acids_dict.values()}, name=input_sequences.index(i)))
display(composition_table)
print(amino_acids_dict.keys())
for i in input_sequences:
    a_val = sum([abs(composition_table.loc[input_sequences.index(i)][amino_acids_dict[aa]] - amino_values[aa][0]) for aa in amino_acids_dict.keys()])
    b_val = sum([abs(composition_table.loc[input_sequences.index(i)][amino_acids_dict[aa]] - amino_values[aa][1]) for aa in amino_acids_dict.keys()])
    if a_val < b_val:
        table = table.append(pd.Series({'A': a_val, 'B': b_val, 'Group': 'A' }, name=input_sequences.index(i)))
    else:
        table = table.append(pd.Series({'A': a_val, 'B': b_val, 'Group': 'B' }, name=input_sequences.index(i)))

table

C:\Users\HP\AppData\Local\Temp\ipykernel_18396\895441728.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  composition_table = composition_table.append(pd.Series({aa: aas.count(aa)*100/len(aas) for aa in amino_acids_dict.values()}, name=input_sequences.index(i)))
C:\Users\HP\AppData\Local\Temp\ipykernel_18396\895441728.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  composition_table = composition_table.append(pd.Series({aa: aas.count(aa)*100/len(aas) for aa in amino_acids_dict.values()}, name=input_sequences.index(i)))
C:\Users\HP\AppData\Local\Temp\ipykernel_18396\895441728.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  composition_table = composition_table.append(pd.Series({aa: aas.count(aa)*100/len(aas) for aa in amino_acids_dict.values()}, name=input_sequences.index(i)))

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
0,17.910448,5.970149,1.492537,2.985075,1.492537,1.492537,2.985075,5.970149,4.477612,1.492537,8.955224,7.462687,0.000000,1.492537,7.462687,5.970149,10.447761,5.970149,4.477612,1.492537
1,19.117647,2.941176,0.000000,2.941176,0.000000,2.941176,1.470588,14.705882,0.000000,11.764706,13.235294,1.470588,7.352941,5.882353,4.411765,0.000000,1.470588,0.000000,1.470588,8.823529
2,10.596026,3.311258,3.311258,5.960265,0.000000,3.311258,3.973510,15.231788,1.324503,5.298013,5.960265,3.973510,0.662252,5.298013,2.649007,9.933775,4.635762,3.973510,5.298013,5.298013

dict_keys(['Ala', 'Arg', 'Asn', 'Asp', 'Cys', 'Gln', 'Glu', 'Gly', 'His', 'Ile', 'Leu', 'Lys', 'Met', 'Phe', 'Pro', 'Ser', 'Thr', 'Trp', 'Tyr', 'Val'])

C:\Users\HP\AppData\Local\Temp\ipykernel_18396\895441728.py:69: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(pd.Series({'A': a_val, 'B': b_val, 'Group': 'A' }, name=input_sequences.index(i)))
C:\Users\HP\AppData\Local\Temp\ipykernel_18396\895441728.py:69: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(pd.Series({'A': a_val, 'B': b_val, 'Group': 'A' }, name=input_sequences.index(i)))
C:\Users\HP\AppData\Local\Temp\ipykernel_18396\895441728.py:71: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table = table.append(pd.Series({'A': a_val, 'B': b_val, 'Group': 'B' }, name=input_sequences.index(i)))

           A          B Group
0  55.844030  58.523731     A
1  74.514706  76.838235     A
2  38.332252  32.597815     B