In [85]:
import pandas as pd
import numpy as np

amino_acids = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']

input_sequences = [
    'RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA',
    'AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA',
    'AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI'
]

for i in input_sequences:
    pair_preference_table_a = pd.DataFrame(index=amino_acids, columns=amino_acids)
    for aa in amino_acids:
        for j in amino_acids:
            if i.count(aa+j) != 0:
                # print(i.count(j+aa), i.count(aa+j))
                pair_preference_table_a[j][aa] = i.count(aa+j)*100/(list(i).count(aa)+list(i).count(j))
    pair_preference_table_a = pair_preference_table_a.fillna(0)
    print(i)
    display(pair_preference_table_a)
    pair_preference_table_a = pair_preference_table_a.replace(0, np.NaN)
    top_10_values = pair_preference_table_a.stack().sort_values(ascending=False).head(10)
    display(pd.DataFrame(top_10_values, columns=['Value']).reset_index())

for i in input_sequences:
    pair_preference_table_b = pd.DataFrame(index=amino_acids, columns=amino_acids)
    for aa in amino_acids:
        for j in amino_acids:
            if i.count(aa+j) != 0:
                pair_preference_table_b[j][aa] = i.count(aa+j)*100/(len(i)-1)
    pair_preference_table_b = pair_preference_table_b.fillna(0)
    print(i)
    display(pair_preference_table_b)
    pair_preference_table_b = pair_preference_table_b.replace(0, np.NaN)
    top_10_values = pair_preference_table_a.stack().sort_values(ascending=False).head(10)
    display(pd.DataFrame(top_10_values, columns=['Value']).reset_index())

for i in input_sequences:
    pair_preference_table_c = pd.DataFrame(index=amino_acids, columns=amino_acids)
    for aa in amino_acids:
        for j in amino_acids:
            if i.count(aa+j) != 0:
                pair_preference_table_c[j][aa] = i.count(aa+j)*100/(list(i).count(aa)*list(i).count(j))
    pair_preference_table_c = pair_preference_table_c.fillna(0)
    print(i)
    display(pair_preference_table_c)
    pair_preference_table_c = pair_preference_table_c.replace(0, np.NaN)
    top_10_values = pair_preference_table_a.stack().sort_values(ascending=False).head(10)
    display(pd.DataFrame(top_10_values, columns=['Value']).reset_index())

RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,12.500000,0.000000,0.0,0.0,0.0,0.000000,0.000000,6.250000,0.000000,0.0,11.111111,0.000000,0,0.0,0.000000,6.250000,15.789474,6.250000,0.000000,0.000000
R,6.250000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,14.285714,0.0,0.000000,0.000000,0,0.0,11.111111,0.000000,0.000000,12.500000,0.000000,0.000000
N,0.000000,20.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D,0.000000,0.000000,0.0,0.0,0.0,0.000000,25.000000,16.666667,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
C,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,50.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,16.666667,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
E,7.142857,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000
G,0.000000,0.000000,0.0,0.0,20.0,0.000000,0.000000,0.000000,0.000000,20.0,10.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,14.285714,0.000000
H,13.333333,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,16.666667,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
I,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,16.666667,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
L,5.555556,0.000000,0.0,12.5,0.0,0.000000,0.000000,0.000000,11.111111,0.0,8.333333,9.090909,0,0.0,0.000000,0.000000,7.692308,0.000000,0.000000,0.000000
K,5.882353,0.000000,0.0,0.0,0.0,16.666667,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,10.000000,11.111111,0.000000,11.111111,0.000000,0.000000
M,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
F,0.000000,0.000000,50.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
P,0.000000,0.000000,0.0,0.0,0.0,0.000000,14.285714,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,11.111111,8.333333,11.111111,0.000000,16.666667
S,0.000000,12.500000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,10.000000,11.111111,0,0.0,0.000000,0.000000,0.000000,0.000000,14.285714,0.000000
T,10.526316,9.090909,0.0,0.0,0.0,0.000000,0.000000,9.090909,0.000000,0.0,0.000000,8.333333,0,0.0,16.666667,0.000000,0.000000,0.000000,0.000000,0.000000
W,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,11.111111,12.500000,18.181818,0.000000,0.000000,0.000000
Y,6.666667,0.000000,0.0,20.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,11.111111,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
V,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,20.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

  level_0 level_1      Value
0       F       N  50.000000
1       C       F  50.000000
2       D       E  25.000000
3       N       R  20.000000
4       G       I  20.000000
5       G       C  20.000000
6       E       Y  20.000000
7       V       G  20.000000
8       Y       D  20.000000
9       W       T  18.181818

AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,15.384615,6.666667,0,0.0,0,0.000000,0.0,0.000000,0,14.285714,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,15.789474
R,0.000000,0.000000,0,0.0,0,25.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,33.333333,0,0.0,0.000000
N,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
D,6.666667,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,9.090909,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
C,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
Q,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,16.666667,20.000000,0,0.000000,0,0.0,0.000000
E,0.000000,0.000000,0,0.0,0,0.000000,0.0,9.090909,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
G,8.695652,0.000000,0,0.0,0,0.000000,0.0,5.000000,0,11.111111,21.052632,9.090909,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
H,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
I,4.761905,0.000000,0,0.0,0,0.000000,0.0,16.666667,0,0.000000,5.882353,0.000000,0.000000,0.000000,18.181818,0,0.000000,0,0.0,7.142857
L,4.545455,9.090909,0,0.0,0,0.000000,10.0,10.526316,0,5.882353,5.555556,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,10.0,6.666667
K,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000,0,0.000000,0,0.0,0.000000
M,0.000000,0.000000,0,0.0,0,0.000000,0.0,13.333333,0,7.692308,0.000000,0.000000,10.000000,11.111111,0.000000,0,0.000000,0,0.0,0.000000
F,5.882353,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,8.333333,7.692308,0.000000,0.000000,12.500000,0.000000,0,0.000000,0,0.0,0.000000
P,0.000000,0.000000,0,20.0,0,0.000000,0.0,0.000000,0,0.000000,8.333333,0.000000,12.500000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
S,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
T,0.000000,0.000000,0,0.0,0,33.333333,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
W,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,0.000000
Y,0.000000,0.000000,0,0.0,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.0,14.285714
V,5.263158,0.000000,0,12.5,0,0.000000,0.0,6.250000,0,0.000000,0.000000,0.000000,27.272727,0.000000,0.000000,0,0.000000,0,0.0,0.000000

  level_0 level_1      Value
0       T       Q  33.333333
1       R       T  33.333333
2       V       M  27.272727
3       R       Q  25.000000
4       G       L  21.052632
5       P       D  20.000000
6       K       F  20.000000
7       Q       P  20.000000
8       I       P  18.181818
9       Q       F  16.666667

AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,9.375000,0.000000,4.761905,4.000000,0,0.000000,0.000000,15.384615,0.0,4.166667,0.000000,0.000000,0.000000,4.166667,5.000000,0.000000,4.347826,0.000000,0.000000,4.166667
R,4.761905,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.0,7.692308,14.285714,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.692308
N,4.761905,0.000000,0.000000,7.142857,0,0.000000,0.000000,3.571429,0.0,0.000000,7.142857,0.000000,0.000000,7.692308,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D,4.000000,7.142857,0.000000,0.000000,0,7.142857,6.666667,3.125000,0.0,0.000000,0.000000,6.666667,0.000000,0.000000,0.000000,4.166667,0.000000,6.666667,0.000000,5.882353
C,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,10.000000,0.000000,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,11.111111,10.000000,8.333333,0.000000,0.000000,0.000000
E,4.545455,0.000000,0.000000,6.666667,0,0.000000,0.000000,6.896552,0.0,0.000000,0.000000,0.000000,0.000000,7.142857,0.000000,4.761905,0.000000,0.000000,0.000000,0.000000
G,7.692308,3.571429,0.000000,9.375000,0,7.142857,0.000000,2.173913,0.0,6.451613,9.375000,3.448276,4.166667,0.000000,0.000000,2.631579,3.333333,0.000000,6.451613,6.451613
H,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.882353,0.000000,0.000000,10.000000,0.000000
I,0.000000,0.000000,0.000000,0.000000,0,0.000000,14.285714,6.451613,10.0,0.000000,0.000000,7.142857,0.000000,0.000000,8.333333,0.000000,0.000000,0.000000,0.000000,0.000000
L,0.000000,0.000000,7.142857,0.000000,0,0.000000,0.000000,6.250000,0.0,0.000000,0.000000,13.333333,0.000000,5.882353,0.000000,8.333333,6.250000,0.000000,0.000000,0.000000
K,0.000000,0.000000,0.000000,0.000000,0,9.090909,0.000000,0.000000,12.5,7.142857,0.000000,0.000000,0.000000,7.142857,10.000000,4.761905,0.000000,0.000000,0.000000,0.000000
M,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.500000,0.000000,0.000000,0.000000
F,12.500000,0.000000,0.000000,0.000000,0,0.000000,7.142857,0.000000,0.0,6.250000,0.000000,0.000000,0.000000,0.000000,0.000000,4.347826,0.000000,0.000000,6.250000,6.250000
P,0.000000,0.000000,11.111111,0.000000,0,0.000000,0.000000,0.000000,0.0,8.333333,0.000000,0.000000,0.000000,8.333333,0.000000,0.000000,0.000000,0.000000,0.000000,8.333333
S,3.225806,0.000000,5.000000,0.000000,0,0.000000,0.000000,5.263158,0.0,4.347826,12.500000,0.000000,0.000000,4.347826,0.000000,3.333333,4.545455,9.523810,4.347826,4.347826
T,0.000000,8.333333,0.000000,0.000000,0,0.000000,0.000000,10.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.545455,0.000000,0.000000,13.333333,0.000000
W,0.000000,0.000000,0.000000,20.000000,0,9.090909,8.333333,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.333333,0.000000,0.000000
Y,0.000000,7.692308,0.000000,0.000000,0,0.000000,7.142857,0.000000,0.0,0.000000,0.000000,7.142857,0.000000,0.000000,0.000000,8.695652,6.666667,14.285714,0.000000,0.000000
V,4.166667,7.692308,0.000000,0.000000,0,0.000000,0.000000,9.677419,0.0,0.000000,0.000000,0.000000,0.000000,6.250000,0.000000,4.347826,0.000000,0.000000,6.250000,0.000000

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000

RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,4.545455,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,3.030303,0.000000,0,0.000000,0.000000,1.515152,4.545455,1.515152,0.000000,0.000000
R,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0,0.000000,1.515152,0.000000,0.000000,1.515152,0.000000,0.000000
N,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,1.515152,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
C,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
E,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000
G,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,1.515152,1.515152,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000
H,3.030303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
I,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
L,1.515152,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,1.515152,1.515152,0,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000
K,1.515152,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,1.515152,1.515152,0.000000,1.515152,0.000000,0.000000
M,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
F,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
P,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,1.515152,1.515152,1.515152,0.000000,1.515152
S,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,1.515152,0,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000
T,3.030303,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,1.515152,0,0.000000,3.030303,0.000000,0.000000,0.000000,0.000000,0.000000
W,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,1.515152,1.515152,3.030303,0.000000,0.000000,0.000000
Y,1.515152,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
V,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000

AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,5.970149,1.492537,0,0.000000,0,0.000000,0.000000,0.000000,0,4.477612,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,4.477612
R,0.000000,0.000000,0,0.000000,0,1.492537,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1.492537,0,0.000000,0.000000
N,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
D,1.492537,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,1.492537,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
C,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
Q,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,1.492537,1.492537,0,0.000000,0,0.000000,0.000000
E,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,1.492537,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
G,2.985075,0.000000,0,0.000000,0,0.000000,0.000000,1.492537,0,2.985075,5.970149,1.492537,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
H,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
I,1.492537,0.000000,0,0.000000,0,0.000000,0.000000,4.477612,0,0.000000,1.492537,0.000000,0.000000,0.000000,2.985075,0,0.000000,0,0.000000,1.492537
L,1.492537,1.492537,0,0.000000,0,0.000000,1.492537,2.985075,0,1.492537,1.492537,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,1.492537,1.492537
K,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,1.492537,0.000000,0,0.000000,0,0.000000,0.000000
M,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,2.985075,0,1.492537,0.000000,0.000000,1.492537,1.492537,0.000000,0,0.000000,0,0.000000,0.000000
F,1.492537,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,1.492537,1.492537,0.000000,0.000000,1.492537,0.000000,0,0.000000,0,0.000000,0.000000
P,0.000000,0.000000,0,1.492537,0,0.000000,0.000000,0.000000,0,0.000000,1.492537,0.000000,1.492537,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
S,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
T,0.000000,0.000000,0,0.000000,0,1.492537,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
W,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
Y,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,1.492537
V,1.492537,0.000000,0,1.492537,0,0.000000,0.000000,1.492537,0,0.000000,0.000000,0.000000,4.477612,0.000000,0.000000,0,0.000000,0,0.000000,0.000000

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000

AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,2.000000,0.000000,0.666667,0.666667,0,0.000000,0.000000,4.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667,0.666667,0.000000,0.666667,0.000000,0.000000,0.666667
R,0.666667,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.666667,1.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667
N,0.666667,0.000000,0.000000,0.666667,0,0.000000,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D,0.666667,0.666667,0.000000,0.000000,0,0.666667,0.666667,0.666667,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.666667
C,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.666667,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,1.333333,0.666667,0.000000,0.000000,0.000000
E,0.666667,0.000000,0.000000,0.666667,0,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000
G,2.000000,0.666667,0.000000,2.000000,0,1.333333,0.000000,0.666667,0.000000,1.333333,2.000000,0.666667,0.666667,0.000000,0.000000,0.666667,0.666667,0.000000,1.333333,1.333333
H,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000
I,0.000000,0.000000,0.000000,0.000000,0,0.000000,1.333333,1.333333,0.666667,0.000000,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000
L,0.000000,0.000000,0.666667,0.000000,0,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,1.333333,0.000000,0.666667,0.000000,1.333333,0.666667,0.000000,0.000000,0.000000
K,0.000000,0.000000,0.000000,0.000000,0,0.666667,0.000000,0.000000,0.666667,0.666667,0.000000,0.000000,0.000000,0.666667,0.666667,0.666667,0.000000,0.000000,0.000000,0.000000
M,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000
F,2.000000,0.000000,0.000000,0.000000,0,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.666667,0.666667
P,0.000000,0.000000,0.666667,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667
S,0.666667,0.000000,0.666667,0.000000,0,0.000000,0.000000,1.333333,0.000000,0.666667,2.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.666667,1.333333,0.666667,0.666667
T,0.000000,0.666667,0.000000,0.000000,0,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,1.333333,0.000000
W,0.000000,0.000000,0.000000,2.000000,0,0.666667,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000
Y,0.000000,0.666667,0.000000,0.000000,0,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,1.333333,0.666667,1.333333,0.000000,0.000000
V,0.666667,0.666667,0.000000,0.000000,0,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000

RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,2.083333,0.000000,0.0,0.000000,0.0,0.0,0.0,2.083333,0.000000,0.0,2.777778,0.000000,0,0.0,0.000000,2.083333,3.571429,2.083333,0.000000,0.0
R,2.083333,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,8.333333,0.0,0.000000,0.000000,0,0.0,5.000000,0.000000,0.000000,6.250000,0.000000,0.0
N,0.000000,25.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
D,0.000000,0.000000,0.0,0.000000,0.0,0.0,25.0,12.500000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
C,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,100.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
Q,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,20.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
E,4.166667,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,16.666667,0.0
G,0.000000,0.000000,0.0,0.000000,25.0,0.0,0.0,0.000000,0.000000,25.0,4.166667,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,8.333333,0.0
H,5.555556,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,11.111111,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
I,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,20.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
L,1.388889,0.000000,0.0,8.333333,0.0,0.0,0.0,0.000000,5.555556,0.0,2.777778,3.333333,0,0.0,0.000000,0.000000,2.380952,0.000000,0.000000,0.0
K,1.666667,0.000000,0.0,0.000000,0.0,20.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,4.000000,5.000000,0.000000,5.000000,0.000000,0.0
M,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
F,0.000000,0.000000,100.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
P,0.000000,0.000000,0.0,0.000000,0.0,0.0,10.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,5.000000,2.857143,5.000000,0.000000,20.0
S,0.000000,6.250000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,4.166667,5.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,8.333333,0.0
T,2.380952,3.571429,0.0,0.000000,0.0,0.0,0.0,3.571429,0.000000,0.0,0.000000,2.857143,0,0.0,5.714286,0.000000,0.000000,0.000000,0.000000,0.0
W,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,5.000000,6.250000,7.142857,0.000000,0.000000,0.0
Y,2.777778,0.000000,0.0,16.666667,0.0,0.0,0.0,0.000000,0.000000,0.0,5.555556,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
V,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,25.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000

AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,2.366864,3.846154,0,0.000000,0,0.0,0.000000,0.000000,0,2.884615,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,3.846154
R,0.000000,0.000000,0,0.000000,0,25.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,50.0,0,0.000000,0.000000
N,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
D,3.846154,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,5.555556,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
C,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
Q,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,12.50,16.666667,0,0.0,0,0.000000,0.000000
E,0.000000,0.000000,0,0.000000,0,0.0,0.000000,10.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
G,1.538462,0.000000,0,0.000000,0,0.0,0.000000,1.000000,0,2.500000,4.444444,10.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
H,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
I,0.961538,0.000000,0,0.000000,0,0.0,0.000000,3.750000,0,0.000000,1.388889,0.0,0.000000,0.00,8.333333,0,0.0,0,0.000000,2.083333
L,0.854701,5.555556,0,0.000000,0,0.0,11.111111,2.222222,0,1.388889,1.234568,0.0,0.000000,0.00,0.000000,0,0.0,0,11.111111,1.851852
K,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,25.00,0.000000,0,0.0,0,0.000000,0.000000
M,0.000000,0.000000,0,0.000000,0,0.0,0.000000,4.000000,0,2.500000,0.000000,0.0,4.000000,5.00,0.000000,0,0.0,0,0.000000,0.000000
F,1.923077,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,3.125000,2.777778,0.0,0.000000,6.25,0.000000,0,0.0,0,0.000000,0.000000
P,0.000000,0.000000,0,16.666667,0,0.0,0.000000,0.000000,0,0.000000,3.703704,0.0,6.666667,0.00,0.000000,0,0.0,0,0.000000,0.000000
S,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
T,0.000000,0.000000,0,0.000000,0,50.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
W,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000
Y,0.000000,0.000000,0,0.000000,0,0.0,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.00,0.000000,0,0.0,0,0.000000,16.666667
V,1.282051,0.000000,0,8.333333,0,0.0,0.000000,1.666667,0,0.000000,0.000000,0.0,10.000000,0.00,0.000000,0,0.0,0,0.000000,0.000000

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000

AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,1.171875,0.000000,1.250000,0.694444,0,0.000000,0.000000,1.630435,0.000000,0.781250,0.000000,0.000000,0.000000,0.781250,1.562500,0.000000,0.892857,0.000000,0.000000,0.781250
R,1.250000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,2.500000,4.444444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.500000
N,1.250000,0.000000,0.000000,2.222222,0,0.000000,0.000000,0.869565,0.000000,0.000000,2.222222,0.000000,0.000000,2.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D,0.694444,2.222222,0.000000,0.000000,0,2.222222,1.851852,0.483092,0.000000,0.000000,0.000000,1.851852,0.000000,0.000000,0.000000,0.740741,0.000000,1.851852,0.000000,1.388889
C,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,4.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.666667,2.857143,0.000000,0.000000,0.000000
E,1.041667,0.000000,0.000000,1.851852,0,0.000000,0.000000,1.449275,0.000000,0.000000,0.000000,0.000000,0.000000,2.083333,0.000000,1.111111,0.000000,0.000000,0.000000,0.000000
G,0.815217,0.869565,0.000000,1.449275,0,1.739130,0.000000,0.189036,0.000000,1.086957,1.449275,0.724638,4.347826,0.000000,0.000000,0.289855,0.621118,0.000000,1.086957,1.086957
H,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.333333,0.000000,0.000000,6.250000,0.000000
I,0.000000,0.000000,0.000000,0.000000,0,0.000000,4.166667,1.086957,6.250000,0.000000,0.000000,2.083333,0.000000,0.000000,3.125000,0.000000,0.000000,0.000000,0.000000,0.000000
L,0.000000,0.000000,2.222222,0.000000,0,0.000000,0.000000,0.966184,0.000000,0.000000,0.000000,3.703704,0.000000,1.388889,0.000000,1.481481,1.587302,0.000000,0.000000,0.000000
K,0.000000,0.000000,0.000000,0.000000,0,3.333333,0.000000,0.000000,8.333333,2.083333,0.000000,0.000000,0.000000,2.083333,4.166667,1.111111,0.000000,0.000000,0.000000,0.000000
M,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.285714,0.000000,0.000000,0.000000
F,2.343750,0.000000,0.000000,0.000000,0,0.000000,2.083333,0.000000,0.000000,1.562500,0.000000,0.000000,0.000000,0.000000,0.000000,0.833333,0.000000,0.000000,1.562500,1.562500
P,0.000000,0.000000,5.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,3.125000,0.000000,0.000000,0.000000,3.125000,0.000000,0.000000,0.000000,0.000000,0.000000,3.125000
S,0.416667,0.000000,1.333333,0.000000,0,0.000000,0.000000,0.579710,0.000000,0.833333,2.222222,0.000000,0.000000,0.833333,0.000000,0.444444,0.952381,2.222222,0.833333,0.833333
T,0.000000,2.857143,0.000000,0.000000,0,0.000000,0.000000,1.863354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.952381,0.000000,0.000000,3.571429,0.000000
W,0.000000,0.000000,0.000000,5.555556,0,3.333333,2.777778,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.777778,0.000000,0.000000
Y,0.000000,2.500000,0.000000,0.000000,0,0.000000,2.083333,0.000000,0.000000,0.000000,0.000000,2.083333,0.000000,0.000000,0.000000,1.666667,1.785714,4.166667,0.000000,0.000000
V,0.781250,2.500000,0.000000,0.000000,0,0.000000,0.000000,1.630435,0.000000,0.000000,0.000000,0.000000,0.000000,1.562500,0.000000,0.833333,0.000000,0.000000,1.562500,0.000000

  level_0 level_1      Value
0       W       D  20.000000
1       A       G  15.384615
2       R       L  14.285714
3       Y       W  14.285714
4       I       E  14.285714
5       T       Y  13.333333
6       L       K  13.333333
7       F       A  12.500000
8       K       H  12.500000
9       S       L  12.500000