In [68]:
import pandas as pd
import numpy as np

amino_acids = ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']

input_sequences = [
    'RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA',
    'AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA',
    'AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI'
]

for i in input_sequences:
    pair_preference_table_a = pd.DataFrame(index=amino_acids, columns=amino_acids)
    for aa in amino_acids:
        for j in amino_acids:
            if i.count(aa+j) != 0:
                pair_preference_table_a[aa][j] = i.count(aa+j)*100/(list(i).count(aa)+list(i).count(j))
    pair_preference_table_a = pair_preference_table_a.fillna(0)
    print(i)
    display(pair_preference_table_a)
    pair_preference_table_a = pair_preference_table_a.replace(0, np.NaN)
    top_10_values = pair_preference_table_a.stack().sort_values(ascending=False).head(10)
    display(pd.DataFrame(top_10_values, columns=['Value']))

for i in input_sequences:
    pair_preference_table_b = pd.DataFrame(index=amino_acids, columns=amino_acids)
    for aa in amino_acids:
        for j in amino_acids:
            if i.count(aa+j) != 0:
                pair_preference_table_b[aa][j] = i.count(aa+j)*100/(len(i)-1)
    pair_preference_table_b = pair_preference_table_b.fillna(0)
    print(i)
    display(pair_preference_table_b)
    pair_preference_table_a = pair_preference_table_a.replace(0, np.NaN)
    top_10_values = pair_preference_table_a.stack().sort_values(ascending=False).head(10)
    display(pd.DataFrame(top_10_values, columns=['Value']))

for i in input_sequences:
    pair_preference_table_c = pd.DataFrame(index=amino_acids, columns=amino_acids)
    for aa in amino_acids:
        for j in amino_acids:
            if i.count(aa+j) != 0:
                pair_preference_table_c[aa][j] = i.count(aa+j)*100/(list(i).count(aa)*list(i).count(j))
    pair_preference_table_c = pair_preference_table_c.fillna(0)
    print(i)
    display(pair_preference_table_c)
    pair_preference_table_a = pair_preference_table_a.replace(0, np.NaN)
    top_10_values = pair_preference_table_a.stack().sort_values(ascending=False).head(10)
    display(pd.DataFrame(top_10_values, columns=['Value']))

RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,12.500000,6.250000,0.0,0.000000,0.0,0.000000,7.142857,0.000000,13.333333,0.000000,5.555556,5.882353,0,0.0,0.000000,0.000000,10.526316,0.000000,6.666667,0.0
R,0.000000,0.000000,20.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,12.500000,9.090909,0.000000,0.000000,0.0
N,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,50.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
D,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,12.500000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,20.000000,0.0
C,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
Q,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.666667,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
E,0.000000,0.000000,0.0,25.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,14.285714,0.000000,0.000000,0.000000,0.000000,0.0
G,6.250000,0.000000,0.0,16.666667,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,0.000000,9.090909,0.000000,0.000000,20.0
H,0.000000,14.285714,0.0,0.000000,0.0,0.000000,0.000000,0.000000,16.666667,0.000000,11.111111,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
I,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
L,11.111111,0.000000,0.0,0.000000,0.0,0.000000,0.000000,10.000000,0.000000,0.000000,8.333333,0.000000,0,0.0,0.000000,10.000000,0.000000,0.000000,11.111111,0.0
K,0.000000,0.000000,0.0,0.000000,0.0,16.666667,0.000000,0.000000,0.000000,16.666667,9.090909,0.000000,0,0.0,0.000000,11.111111,8.333333,0.000000,0.000000,0.0
M,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
F,0.000000,0.000000,0.0,0.000000,50.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
P,0.000000,11.111111,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,0,0.0,0.000000,0.000000,16.666667,11.111111,0.000000,0.0
S,6.250000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.111111,0,0.0,11.111111,0.000000,0.000000,12.500000,0.000000,0.0
T,15.789474,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,7.692308,0.000000,0,0.0,8.333333,0.000000,0.000000,18.181818,0.000000,0.0
W,6.250000,12.500000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.111111,0,0.0,11.111111,0.000000,0.000000,0.000000,0.000000,0.0
Y,0.000000,0.000000,0.0,0.000000,0.0,0.000000,20.000000,14.285714,0.000000,0.000000,0.000000,0.000000,0,0.0,0.000000,14.285714,0.000000,0.000000,0.000000,0.0
V,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.0,16.666667,0.000000,0.000000,0.000000,0.000000,0.0

         Value
F C  50.000000
N F  50.000000
E D  25.000000
G V  20.000000
Y E  20.000000
R N  20.000000
I G  20.000000
D Y  20.000000
C G  20.000000
T W  18.181818

AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,15.384615,0.000000,0,6.666667,0,0.000000,0.000000,8.695652,0,4.761905,4.545455,0.0,0.000000,5.882353,0.000000,0,0.000000,0,0.000000,5.263158
R,6.666667,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,9.090909,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
N,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
D,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,20.000000,0,0.000000,0,0.000000,12.500000
C,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
Q,0.000000,25.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,33.333333,0,0.000000,0.000000
E,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,10.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
G,0.000000,0.000000,0,0.000000,0,0.000000,9.090909,5.000000,0,16.666667,10.526316,0.0,13.333333,0.000000,0.000000,0,0.000000,0,0.000000,6.250000
H,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
I,14.285714,0.000000,0,0.000000,0,0.000000,0.000000,11.111111,0,0.000000,5.882353,0.0,7.692308,8.333333,0.000000,0,0.000000,0,0.000000,0.000000
L,0.000000,0.000000,0,9.090909,0,0.000000,0.000000,21.052632,0,5.882353,5.555556,0.0,0.000000,7.692308,8.333333,0,0.000000,0,0.000000,0.000000
K,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,9.090909,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
M,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,10.000000,0.000000,12.500000,0,0.000000,0,0.000000,27.272727
F,0.000000,0.000000,0,0.000000,0,16.666667,0.000000,0.000000,0,0.000000,0.000000,20.0,11.111111,12.500000,0.000000,0,0.000000,0,0.000000,0.000000
P,0.000000,0.000000,0,0.000000,0,20.000000,0.000000,0.000000,0,18.181818,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
S,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
T,0.000000,33.333333,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
W,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
Y,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,10.000000,0.0,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
V,15.789474,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,7.142857,6.666667,0.0,0.000000,0.000000,0.000000,0,0.000000,0,14.285714,0.000000

         Value
T R  33.333333
Q T  33.333333
M V  27.272727
Q R  25.000000
L G  21.052632
P Q  20.000000
F K  20.000000
D P  20.000000
P I  18.181818
G I  16.666667

AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,9.375000,4.761905,4.761905,4.000000,0,0.000000,4.545455,7.692308,0.000000,0.000000,0.000000,0.000000,0.0,12.500000,0.000000,3.225806,0.000000,0.000000,0.000000,4.166667
R,0.000000,0.000000,0.000000,7.142857,0,0.000000,0.000000,3.571429,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,8.333333,0.000000,7.692308,7.692308
N,4.761905,0.000000,0.000000,0.000000,0,10.000000,0.000000,0.000000,0.000000,0.000000,7.142857,0.000000,0.0,0.000000,11.111111,5.000000,0.000000,0.000000,0.000000,0.000000
D,4.000000,0.000000,7.142857,0.000000,0,0.000000,6.666667,9.375000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,20.000000,0.000000,0.000000
C,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.000000,7.142857,0,0.000000,0.000000,7.142857,0.000000,0.000000,0.000000,9.090909,0.0,0.000000,0.000000,0.000000,0.000000,9.090909,0.000000,0.000000
E,0.000000,0.000000,0.000000,6.666667,0,0.000000,0.000000,0.000000,0.000000,14.285714,0.000000,0.000000,0.0,7.142857,0.000000,0.000000,0.000000,8.333333,7.142857,0.000000
G,15.384615,0.000000,3.571429,3.125000,0,0.000000,6.896552,2.173913,0.000000,6.451613,6.250000,0.000000,0.0,0.000000,0.000000,5.263158,10.000000,0.000000,0.000000,9.677419
H,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,10.000000,0.000000,12.500000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
I,4.166667,7.692308,0.000000,0.000000,0,0.000000,0.000000,6.451613,0.000000,0.000000,0.000000,7.142857,0.0,6.250000,8.333333,4.347826,0.000000,0.000000,0.000000,0.000000
L,0.000000,14.285714,7.142857,0.000000,0,0.000000,0.000000,9.375000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,12.500000,0.000000,0.000000,0.000000,0.000000
K,0.000000,0.000000,0.000000,6.666667,0,0.000000,0.000000,3.448276,0.000000,7.142857,13.333333,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,7.142857,0.000000
M,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,4.166667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
F,4.166667,0.000000,7.692308,0.000000,0,0.000000,7.142857,0.000000,0.000000,0.000000,5.882353,7.142857,0.0,0.000000,8.333333,4.347826,0.000000,0.000000,0.000000,6.250000
P,5.000000,0.000000,0.000000,0.000000,0,11.111111,0.000000,0.000000,0.000000,8.333333,0.000000,10.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
S,0.000000,0.000000,0.000000,4.166667,0,10.000000,4.761905,2.631579,5.882353,0.000000,8.333333,4.761905,0.0,4.347826,0.000000,3.333333,4.545455,0.000000,8.695652,4.347826
T,4.347826,0.000000,0.000000,0.000000,0,8.333333,0.000000,3.333333,0.000000,0.000000,6.250000,0.000000,12.5,0.000000,0.000000,4.545455,0.000000,0.000000,6.666667,0.000000
W,0.000000,0.000000,0.000000,6.666667,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,9.523810,0.000000,8.333333,14.285714,0.000000
Y,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,6.451613,10.000000,0.000000,0.000000,0.000000,0.0,6.250000,0.000000,4.347826,13.333333,0.000000,0.000000,6.250000
V,4.166667,7.692308,0.000000,5.882353,0,0.000000,0.000000,6.451613,0.000000,0.000000,0.000000,0.000000,0.0,6.250000,8.333333,4.347826,0.000000,0.000000,0.000000,0.000000

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000

RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,4.545455,1.515152,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,3.030303,0.000000,1.515152,1.515152,0,0.000000,0.000000,0.000000,3.030303,0.000000,1.515152,0.000000
R,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,1.515152,1.515152,0.000000,0.000000,0.000000
N,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
D,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000
C,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
E,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000
G,1.515152,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,1.515152
H,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,1.515152,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
I,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
L,3.030303,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,1.515152,0.000000,0,0.000000,0.000000,1.515152,0.000000,0.000000,1.515152,0.000000
K,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,1.515152,1.515152,0.000000,0,0.000000,0.000000,1.515152,1.515152,0.000000,0.000000,0.000000
M,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
F,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
P,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0,0.000000,0.000000,0.000000,3.030303,1.515152,0.000000,0.000000
S,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0,0.000000,1.515152,0.000000,0.000000,1.515152,0.000000,0.000000
T,4.545455,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0.000000,0,0.000000,1.515152,0.000000,0.000000,3.030303,0.000000,0.000000
W,1.515152,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,0,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000
Y,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.515152,1.515152,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000
V,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,1.515152,0.000000,0.000000,0.000000,0.000000,0.000000

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000

AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,5.970149,0.000000,0,1.492537,0,0.000000,0.000000,2.985075,0,1.492537,1.492537,0.000000,0.000000,1.492537,0.000000,0,0.000000,0,0.000000,1.492537
R,1.492537,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,1.492537,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
N,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
D,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,1.492537,0,0.000000,0,0.000000,1.492537
C,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
Q,0.000000,1.492537,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,1.492537,0,0.000000,0.000000
E,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,1.492537,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
G,0.000000,0.000000,0,0.000000,0,0.000000,1.492537,1.492537,0,4.477612,2.985075,0.000000,2.985075,0.000000,0.000000,0,0.000000,0,0.000000,1.492537
H,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
I,4.477612,0.000000,0,0.000000,0,0.000000,0.000000,2.985075,0,0.000000,1.492537,0.000000,1.492537,1.492537,0.000000,0,0.000000,0,0.000000,0.000000
L,0.000000,0.000000,0,1.492537,0,0.000000,0.000000,5.970149,0,1.492537,1.492537,0.000000,0.000000,1.492537,1.492537,0,0.000000,0,0.000000,0.000000
K,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,1.492537,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
M,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,1.492537,0.000000,1.492537,0,0.000000,0,0.000000,4.477612
F,0.000000,0.000000,0,0.000000,0,1.492537,0.000000,0.000000,0,0.000000,0.000000,1.492537,1.492537,1.492537,0.000000,0,0.000000,0,0.000000,0.000000
P,0.000000,0.000000,0,0.000000,0,1.492537,0.000000,0.000000,0,2.985075,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
S,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
T,0.000000,1.492537,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
W,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
Y,0.000000,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,0.000000,1.492537,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0.000000,0.000000
V,4.477612,0.000000,0,0.000000,0,0.000000,0.000000,0.000000,0,1.492537,1.492537,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,1.492537,0.000000

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000

AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,2.000000,0.666667,0.666667,0.666667,0,0.000000,0.666667,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667
R,0.000000,0.000000,0.000000,0.666667,0,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.666667
N,0.666667,0.000000,0.000000,0.000000,0,0.666667,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667,0.666667,0.000000,0.000000,0.000000,0.000000
D,0.666667,0.000000,0.666667,0.000000,0,0.000000,0.666667,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
C,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.000000,0.666667,0,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000
E,0.000000,0.000000,0.000000,0.666667,0,0.000000,0.000000,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667,0.666667,0.000000
G,4.000000,0.000000,0.666667,0.666667,0,0.000000,1.333333,0.666667,0.000000,1.333333,1.333333,0.000000,0.000000,0.000000,0.000000,1.333333,2.000000,0.000000,0.000000,2.000000
H,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
I,0.666667,0.666667,0.000000,0.000000,0,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.666667,0.666667,0.000000,0.000000,0.000000,0.000000
L,0.000000,1.333333,0.666667,0.000000,0,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
K,0.000000,0.000000,0.000000,0.666667,0,0.000000,0.000000,0.666667,0.000000,0.666667,1.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000
M,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
F,0.666667,0.000000,0.666667,0.000000,0,0.000000,0.666667,0.000000,0.000000,0.000000,0.666667,0.666667,0.000000,0.000000,0.666667,0.666667,0.000000,0.000000,0.000000,0.666667
P,0.666667,0.000000,0.000000,0.000000,0,0.666667,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
S,0.000000,0.000000,0.000000,0.666667,0,1.333333,0.666667,0.666667,0.666667,0.000000,1.333333,0.666667,0.000000,0.666667,0.000000,0.666667,0.666667,0.000000,1.333333,0.666667
T,0.666667,0.000000,0.000000,0.000000,0,0.666667,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000,0.000000,0.666667,0.000000
W,0.000000,0.000000,0.000000,0.666667,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.333333,0.000000,0.666667,1.333333,0.000000
Y,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,1.333333,0.666667,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.666667,1.333333,0.000000,0.000000,0.666667
V,0.666667,0.666667,0.000000,0.666667,0,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.666667,0.666667,0.000000,0.000000,0.000000,0.000000

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000

RATPTRWPVGCFNRPWTKWSYDEALDGIKAAGYAWTGLLTASKPSLHHATATPEYLAALKQKSRHAA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,2.083333,2.083333,0.0,0.0,0.0,0.0,4.166667,0.000000,5.555556,0.0,1.388889,1.666667,0,0.0,0.000000,0.000000,2.380952,0.000000,2.777778,0.0
R,0.000000,0.000000,25.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,6.250000,3.571429,0.000000,0.000000,0.0
N,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,100.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
D,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,8.333333,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,16.666667,0.0
C,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,25.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
Q,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,20.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
E,0.000000,0.000000,0.0,25.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,10.000000,0.000000,0.000000,0.000000,0.000000,0.0
G,2.083333,0.000000,0.0,12.5,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,3.571429,0.000000,0.000000,25.0
H,0.000000,8.333333,0.0,0.0,0.0,0.0,0.000000,0.000000,11.111111,0.0,5.555556,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
I,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,25.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
L,2.777778,0.000000,0.0,0.0,0.0,0.0,0.000000,4.166667,0.000000,0.0,2.777778,0.000000,0,0.0,0.000000,4.166667,0.000000,0.000000,5.555556,0.0
K,0.000000,0.000000,0.0,0.0,0.0,20.0,0.000000,0.000000,0.000000,20.0,3.333333,0.000000,0,0.0,0.000000,5.000000,2.857143,0.000000,0.000000,0.0
M,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
F,0.000000,0.000000,0.0,0.0,100.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
P,0.000000,5.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,4.000000,0,0.0,0.000000,0.000000,5.714286,5.000000,0.000000,0.0
S,2.083333,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,5.000000,0,0.0,5.000000,0.000000,0.000000,6.250000,0.000000,0.0
T,3.571429,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,2.380952,0.000000,0,0.0,2.857143,0.000000,0.000000,7.142857,0.000000,0.0
W,2.083333,6.250000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,5.000000,0,0.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.0
Y,0.000000,0.000000,0.0,0.0,0.0,0.0,16.666667,8.333333,0.000000,0.0,0.000000,0.000000,0,0.0,0.000000,8.333333,0.000000,0.000000,0.000000,0.0
V,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0.0,20.000000,0.000000,0.000000,0.000000,0.000000,0.0

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000

AAAVMMGLAAIGAAIGIGILGGKFLEGAARQPDLIPLLRTQFFIVMGLVDAIPMIAVGLGLYVMFAVA

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,2.366864,0.0,0,3.846154,0,0.000000,0.0,1.538462,0,0.961538,0.854701,0.0,0.0,1.923077,0.000000,0,0.0,0,0.000000,1.282051
R,3.846154,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,5.555556,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
N,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
D,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,16.666667,0,0.0,0,0.000000,8.333333
C,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
Q,0.000000,25.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,50.0,0,0.000000,0.000000
E,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,11.111111,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
G,0.000000,0.0,0,0.000000,0,0.000000,10.0,1.000000,0,3.750000,2.222222,0.0,4.0,0.000000,0.000000,0,0.0,0,0.000000,1.666667
H,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
I,2.884615,0.0,0,0.000000,0,0.000000,0.0,2.500000,0,0.000000,1.388889,0.0,2.5,3.125000,0.000000,0,0.0,0,0.000000,0.000000
L,0.000000,0.0,0,5.555556,0,0.000000,0.0,4.444444,0,1.388889,1.234568,0.0,0.0,2.777778,3.703704,0,0.0,0,0.000000,0.000000
K,0.000000,0.0,0,0.000000,0,0.000000,0.0,10.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
M,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,4.0,0.000000,6.666667,0,0.0,0,0.000000,10.000000
F,0.000000,0.0,0,0.000000,0,12.500000,0.0,0.000000,0,0.000000,0.000000,25.0,5.0,6.250000,0.000000,0,0.0,0,0.000000,0.000000
P,0.000000,0.0,0,0.000000,0,16.666667,0.0,0.000000,0,8.333333,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
S,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
T,0.000000,50.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
W,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
Y,0.000000,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,0.000000,11.111111,0.0,0.0,0.000000,0.000000,0,0.0,0,0.000000,0.000000
V,3.846154,0.0,0,0.000000,0,0.000000,0.0,0.000000,0,2.083333,1.851852,0.0,0.0,0.000000,0.000000,0,0.0,0,16.666667,0.000000

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000

AADVSAAVGATGQSGMTYRLGLSWDWDKSWWQTSTGRLTGYWDAGYTYWEGGDEGAGKHSLSFAPVFVYEFAGDSIKPFIEAGIGVAAFSGTRVGDQNLGSSLNFEDRIGAGLKFANGQSVGVRAIHYSNAGLKQPNDGIESYSLFYKIPI

,A,R,N,D,C,Q,E,G,H,I,L,K,M,F,P,S,T,W,Y,V
A,1.171875,1.250000,1.250000,0.694444,0,0.000000,1.041667,0.815217,0.000000,0.000000,0.000000,0.000000,0.000000,2.343750,0.000,0.416667,0.000000,0.000000,0.000000,0.781250
R,0.000000,0.000000,0.000000,2.222222,0,0.000000,0.000000,0.869565,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,2.857143,0.000000,2.500000,2.500000
N,1.250000,0.000000,0.000000,0.000000,0,4.000000,0.000000,0.000000,0.000000,0.000000,2.222222,0.000000,0.000000,0.000000,5.000,1.333333,0.000000,0.000000,0.000000,0.000000
D,0.694444,0.000000,2.222222,0.000000,0,0.000000,1.851852,1.449275,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,5.555556,0.000000,0.000000
C,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000
Q,0.000000,0.000000,0.000000,2.222222,0,0.000000,0.000000,1.739130,0.000000,0.000000,0.000000,3.333333,0.000000,0.000000,0.000,0.000000,0.000000,3.333333,0.000000,0.000000
E,0.000000,0.000000,0.000000,1.851852,0,0.000000,0.000000,0.000000,0.000000,4.166667,0.000000,0.000000,0.000000,2.083333,0.000,0.000000,0.000000,2.777778,2.083333,0.000000
G,1.630435,0.000000,0.869565,0.483092,0,0.000000,1.449275,0.189036,0.000000,1.086957,0.966184,0.000000,0.000000,0.000000,0.000,0.579710,1.863354,0.000000,0.000000,1.630435
H,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,6.250000,0.000000,8.333333,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000
I,0.781250,2.500000,0.000000,0.000000,0,0.000000,0.000000,1.086957,0.000000,0.000000,0.000000,2.083333,0.000000,1.562500,3.125,0.833333,0.000000,0.000000,0.000000,0.000000
L,0.000000,4.444444,2.222222,0.000000,0,0.000000,0.000000,1.449275,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,2.222222,0.000000,0.000000,0.000000,0.000000
K,0.000000,0.000000,0.000000,1.851852,0,0.000000,0.000000,0.724638,0.000000,2.083333,3.703704,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,2.083333,0.000000
M,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,4.347826,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000
F,0.781250,0.000000,2.500000,0.000000,0,0.000000,2.083333,0.000000,0.000000,0.000000,1.388889,2.083333,0.000000,0.000000,3.125,0.833333,0.000000,0.000000,0.000000,1.562500
P,1.562500,0.000000,0.000000,0.000000,0,5.000000,0.000000,0.000000,0.000000,3.125000,0.000000,4.166667,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000
S,0.000000,0.000000,0.000000,0.740741,0,2.666667,1.111111,0.289855,3.333333,0.000000,1.481481,1.111111,0.000000,0.833333,0.000,0.444444,0.952381,0.000000,1.666667,0.833333
T,0.892857,0.000000,0.000000,0.000000,0,2.857143,0.000000,0.621118,0.000000,0.000000,1.587302,0.000000,14.285714,0.000000,0.000,0.952381,0.000000,0.000000,1.785714,0.000000
W,0.000000,0.000000,0.000000,1.851852,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000,2.222222,0.000000,2.777778,4.166667,0.000000
Y,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,1.086957,6.250000,0.000000,0.000000,0.000000,0.000000,1.562500,0.000,0.833333,3.571429,0.000000,0.000000,1.562500
V,0.781250,2.500000,0.000000,1.388889,0,0.000000,0.000000,1.086957,0.000000,0.000000,0.000000,0.000000,0.000000,1.562500,3.125,0.833333,0.000000,0.000000,0.000000,0.000000

         Value
D W  20.000000
G A  15.384615
E I  14.285714
L R  14.285714
W Y  14.285714
K L  13.333333
Y T  13.333333
A F  12.500000
T M  12.500000
H K  12.500000